CREATE TABLE UserTypes (
	id INTEGER PRIMARY KEY,
	theTypes VARCHAR(50) NOT NULL
);

CREATE TABLE Users (
	id INTEGER PRIMARY KEY,
	startDate DATETIME2 NOT NULL,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	userPassword VARCHAR(50) NOT NULL,
	userTypeId INTEGER FOREIGN KEY REFERENCES UserTypes(id) NOT NULL
);

CREATE TABLE Categories (
	id INTEGER PRIMARY KEY NOT NULL,
	name VARCHAR(50) NOT NULL,
	rankId INTEGER NOT NULL
);

CREATE TABLE Products (
	id INTEGER PRIMARY KEY NOT NULL,
	name VARCHAR(50) NOT NULL,
	theDescription VARCHAR(MAX) NOT NULL,
	imageUrl VARCHAR(50) NOT NULL,
	price MONEY NOT NULL,
	condition VARCHAR(50) NOT NULL,
	theAvailability VARCHAR(50) NOT NULL,
	includes VARCHAR(MAX) NOT NULL,
	categoryId INTEGER FOREIGN KEY REFERENCES Categories(id) NOT NULL,
	isFeatured BIT NOT NULL
);

CREATE TABLE Promotions (
	id INTEGER PRIMARY KEY NOT NULL,
	name VARCHAR(50) NOT NULL,
	theDescription VARCHAR(MAX),
	startDate DATETIME2 NOT NULL,
	endDate DATETIME2 NOT NULL,
	creationDate DATETIME2 NOT NULL,
	salePrice MONEY,
	overallDiscount MONEY,
	validZipCode VARCHAR(50),
	theType VARCHAR(50) NOT NULL
);

CREATE TABLE Carts (
	id INTEGER PRIMARY KEY NOT NULL,
	theStatus VARCHAR(50) NOT NULL,
	creationDate DATETIME2 NOT NULL,
	userId INTEGER FOREIGN KEY REFERENCES Users(id),
	zipCode INTEGER
);

CREATE TABLE CartProducts (
	id INTEGER PRIMARY KEY NOT NULL,
	cartId INTEGER FOREIGN KEY REFERENCES Carts(id) NOT NULL,
	productId INTEGER FOREIGN KEY REFERENCES Products(id) NOT NULL,
	quantity INTEGER NOT NULL
);

CREATE TABLE CartPromotions (
	id INTEGER PRIMARY KEY NOT NULL,
	promotionId INTEGER FOREIGN KEY REFERENCES Promotions(id) NOT NULL,
	productId INTEGER FOREIGN KEY REFERENCES Products(id) NOT NULL
);
